name: goss-org
title: Goss
license: Apache-2.0
website:
  - https://goss.rocks
  - https://github.com/sed-i/goss-org-snap
source-code:
  - https://github.com/goss-org/goss
base: core24
adopt-info: goss
summary: Quick and Easy server testing/validation
description: |
  Goss is a YAML based serverspec alternative tool for validating a server's configuration.
  It eases the process of writing tests by allowing the user to generate tests from the current system state.
  Once the test suite is written they can be executed, waited-on, or served as a health endpoint.

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
  ppc64el:
  s390x:

apps:
  goss:
    command: usr/bin/goss
  dcgoss:
    command: usr/bin/dcgoss
  dgoss:
    command: usr/bin/dgoss
  kgoss:
    command: usr/bin/kgoss

parts:
  goss:
    plugin: go
    source: https://github.com/goss-org/goss
    source-type: git
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always --match=v*.*.* | sed 's/^v//')"
    build-snaps:
      - go/1.24/stable
    build-environment:
      - CGO_ENABLED: "0"
      #- GOFLAGS: -ldflags=-s -ldflags=-w -ldflags="-X github.com/goss-org/goss/util.Version=0.4.9"
      #- GOFLAGS: -ldflags="-w -s -X github.com/goss-org/goss/util.Version=0.4.9"
      - GOFLAGS: -ldflags=-w -ldflags=-s
    build-attributes:
      - enable-patchelf
    organize:
      bin/goss: usr/bin/goss
    stage:
      - usr/bin/goss
    prime:
      - usr/bin/goss

  goss-extras:
    after: [goss]
    plugin: dump
    source: https://github.com/goss-org/goss
    source-type: git
    source-subdir: extras
    organize:
      dcgoss/dcgoss: usr/bin/dcgoss
      dgoss/dgoss: usr/bin/dgoss
      kgoss/kgoss: usr/bin/kgoss
